In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = pd.read_csv('/content/TripAdvisor_RestauarantRecommendation.csv')

In [ ]:
data.head()

Name       Street Address  \
0  Betty Lou's Seafood and Grill     318 Columbus Ave   
1              Coach House Diner        55 State Rt 4   
2               Table Talk Diner  2521 South Rd Ste C   
3                    Sixty Vines     3701 Dallas Pkwy   
4                   The Clam Bar    3914 Brewerton Rd   

                       Location                                          Type  \
0  San Francisco, CA 94133-3908   Seafood, Vegetarian Friendly, Vegan Options   
1     Hackensack, NJ 07601-6337          Diner, American, Vegetarian Friendly   
2   Poughkeepsie, NY 12601-5476          American, Diner, Vegetarian Friendly   
3          Plano, TX 75093-7777       American, Wine Bar, Vegetarian Friendly   
4            Syracuse, NY 13212                        American, Bar, Seafood   

            Reviews No of Reviews  \
0  4.5 of 5 bubbles   243 reviews   
1    4 of 5 bubbles    84 reviews   
2    4 of 5 bubbles   256 reviews   
3  4.5 of 5 bubbles   235 reviews   
4    4 of 5 bubbles   285 reviews   

                                            Comments   Contact Number  \
0                                                NaN  +1 415-757-0569   
1  Both times we were there very late, after 11 P...  +1 201-488-4999   
2  Waitress was very friendly but a little pricey...  +1 845-849-2839   
3  Not sure why I went there for the second time....  +1 469-620-8463   
4  Doesn't look like much from the outside but wa...  +1 315-458-1662   

                                    Trip_advisor Url  \
0  https://www.tripadvisor.com//Restaurant_Review...   
1  https://www.tripadvisor.com//Restaurant_Review...   
2  https://www.tripadvisor.com//Restaurant_Review...   
3  https://www.tripadvisor.com//Restaurant_Review...   
4  https://www.tripadvisor.com//Restaurant_Review...   

                                        Menu Price_Range  
0               Check The Website for a Menu    $$ - $$$  
1               Check The Website for a Menu    $$ - $$$  
2  http://tabletalkdiner.com/menu/breakfast/    $$ - $$$  
3      https://sixtyvines.com/menu/plano-tx/    $$ - $$$  
4               Check The Website for a Menu    $$ - $$$

In [ ]:
# we are suggesting restraunts based on type of food

In [ ]:
data.shape

(3062, 11)

In [ ]:
data.Name.nunique()

2641

In [ ]:
data['Type']

0         Seafood, Vegetarian Friendly, Vegan Options
1                Diner, American, Vegetarian Friendly
2                American, Diner, Vegetarian Friendly
3             American, Wine Bar, Vegetarian Friendly
4                              American, Bar, Seafood
                            ...                      
3057               American, Bar, Vegetarian Friendly
3058                           American, Bar, Seafood
3059                         Steakhouse, Italian, Bar
3060     American, Vegan Options, Gluten Free Options
3061      Italian, Vegetarian Friendly, Vegan Options
Name: Type, Length: 3062, dtype: object

In [ ]:
data1 = data[['Name','Type']]

In [ ]:
data1.isna().sum()

Name     0
Type    13
dtype: int64

In [ ]:
data1 =data1.dropna()

In [ ]:
data1.shape

(3049, 2)

In [ ]:
data1.isna().sum()

Name    0
Type    0
dtype: int64

In [ ]:
data1.head()

Name                                          Type
0  Betty Lou's Seafood and Grill   Seafood, Vegetarian Friendly, Vegan Options
1              Coach House Diner          Diner, American, Vegetarian Friendly
2               Table Talk Diner          American, Diner, Vegetarian Friendly
3                    Sixty Vines       American, Wine Bar, Vegetarian Friendly
4                   The Clam Bar                        American, Bar, Seafood

In [ ]:
indeces = pd.Series(data1.index,index = data1['Name'])

In [ ]:
indeces

Name
Betty Lou's Seafood and Grill       0
Coach House Diner                   1
Table Talk Diner                    2
Sixty Vines                         3
The Clam Bar                        4
                                 ... 
Indigo Kitchen & Ale House       3057
City Vineyard                    3058
BRIO Tuscan Grille               3059
Maywood Pancake house            3060
Porto Leggero                    3061
Length: 3049, dtype: int64

In [ ]:
indeces['Sixty Vines']

3

In [ ]:
data1.dtypes

Name    object
Type    object
dtype: object

In [ ]:
#converting type to vectors

In [ ]:
#basic-method
#bag of birds(count-friendly)
#this method is not sematic or meaning based

In [ ]:
feature =data1['Type'].tolist()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(stop_words='english')

In [ ]:
cv_matrix = cv.fit_transform(feature)

In [ ]:
#cv_matrix

<3049x112 sparse matrix of type '<class 'numpy.int64'>'
	with 11303 stored elements in Compressed Sparse Row format>

In [ ]:
#cv_matrix.toarray()

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]])

In [ ]:
cv_matrix.shape

(3049, 112)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(cv_matrix)

In [ ]:
pd.DataFrame(similarity)

0         1         2         3         4         5         6     \
0     1.000000  0.447214  0.447214  0.400000  0.258199  0.258199  0.000000   
1     0.447214  1.000000  1.000000  0.670820  0.288675  0.000000  0.288675   
2     0.447214  1.000000  1.000000  0.670820  0.288675  0.000000  0.288675   
3     0.400000  0.670820  0.670820  1.000000  0.516398  0.000000  0.516398   
4     0.258199  0.288675  0.288675  0.516398  1.000000  0.333333  0.666667   
...        ...       ...       ...       ...       ...       ...       ...   
3044  0.447214  0.750000  0.750000  0.894427  0.577350  0.000000  0.577350   
3045  0.258199  0.288675  0.288675  0.516398  1.000000  0.333333  0.666667   
3046  0.000000  0.000000  0.000000  0.258199  0.333333  0.333333  0.666667   
3047  0.474342  0.176777  0.176777  0.158114  0.204124  0.000000  0.204124   
3048  0.800000  0.447214  0.447214  0.400000  0.000000  0.258199  0.000000   

      7         8         9     ...      3039  3040      3041      3042  \
0      0.0  0.447214  0.200000  ...  0.516398   0.0  0.258199  0.800000   
1      0.0  0.500000  0.223607  ...  0.866025   0.0  0.288675  0.447214   
2      0.0  0.500000  0.223607  ...  0.866025   0.0  0.288675  0.447214   
3      0.0  0.447214  0.200000  ...  0.774597   0.0  0.258199  0.400000   
4      0.0  0.000000  0.258199  ...  0.333333   0.0  0.666667  0.000000   
...    ...       ...       ...  ...       ...   ...       ...       ...   
3044   0.0  0.500000  0.223607  ...  0.866025   0.0  0.288675  0.447214   
3045   0.0  0.000000  0.258199  ...  0.333333   0.0  0.666667  0.000000   
3046   0.0  0.288675  0.258199  ...  0.000000   0.0  0.000000  0.258199   
3047   0.0  0.000000  0.790569  ...  0.204124   0.0  0.204124  0.474342   
3048   0.0  0.670820  0.200000  ...  0.516398   0.0  0.000000  1.000000   

          3043      3044      3045      3046      3047      3048  
0     0.447214  0.447214  0.258199  0.000000  0.474342  0.800000  
1     0.500000  0.750000  0.288675  0.000000  0.176777  0.447214  
2     0.500000  0.750000  0.288675  0.000000  0.176777  0.447214  
3     0.447214  0.894427  0.516398  0.258199  0.158114  0.400000  
4     0.000000  0.577350  1.000000  0.333333  0.204124  0.000000  
...        ...       ...       ...       ...       ...       ...  
3044  0.500000  1.000000  0.577350  0.288675  0.176777  0.447214  
3045  0.000000  0.577350  1.000000  0.333333  0.204124  0.000000  
3046  0.000000  0.288675  0.333333  1.000000  0.000000  0.258199  
3047  0.000000  0.176777  0.204124  0.000000  1.000000  0.474342  
3048  0.447214  0.447214  0.000000  0.258199  0.474342  1.000000  

[3049 rows x 3049 columns]

In [ ]:
similarity[3]

array([0.4       , 0.67082039, 0.67082039, ..., 0.25819889, 0.15811388,
       0.4       ])

In [ ]:
list(enumerate(similarity[3]))

In [ ]:
def rest_rec_sys(name,similarity=similarity):
  index = indeces[name]
  similarity_score = list(enumerate(similarity[index]))
  similarity_score = sorted(similarity_score,key = lambda x:x[1],reverse = True)
  similarity_score = similarity_score[0:11]
  res_indices =[i[0] for i in similarity_score]
  res_rec = data1['Name'].iloc[res_indices]
  return res_rec

In [ ]:
rest_rec_sys('The Clam Bar')

4                            The Clam Bar
57                        Buzzard Billy's
62                     Cedars at Pier One
66     Maxie's Supper Club and Oyster Bar
122               Duke's Huntington Beach
189              River Station Restaurant
247                       Fish City Grill
304                    Tony's On the Pier
374                         Pacific Grill
393              Anthony's Woodfire Grill
436                       The Crow's Nest
Name: Name, dtype: object

Suggesting restraunts based on type of comments

In [ ]:
data['Comments']

0                                                     NaN
1       Both times we were there very late, after 11 P...
2       Waitress was very friendly but a little pricey...
3       Not sure why I went there for the second time....
4       Doesn't look like much from the outside but wa...
                              ...                        
3057    We had to wait a few minutes to get it but it ...
3058    Came here to see Andrea Gibson perform, we wer...
3059    We come to Brio once a month. They are good fo...
3060    Stopped in yesterday for Breakfast. When in Je...
3061    First time for dinner. 2 couples. Delicious mu...
Name: Comments, Length: 3062, dtype: object

In [ ]:
data2= data[['Name','Comments']]

In [ ]:
data2.isna().sum()

Name          0
Comments    615
dtype: int64

In [ ]:
data2=data2.dropna()

In [ ]:
data2.reset_index(drop=True,inplace=True)

In [ ]:
data2.head()

Name  \
0                     Coach House Diner   
1                      Table Talk Diner   
2                           Sixty Vines   
3                          The Clam Bar   
4  Black Angus Steakhouse - Federal Way   

                                            Comments  
0  Both times we were there very late, after 11 P...  
1  Waitress was very friendly but a little pricey...  
2  Not sure why I went there for the second time....  
3  Doesn't look like much from the outside but wa...  
4  This is an easy any time place to have dinner!...

In [ ]:
indices = pd.Series(data2.index,index=data2['Name'])

In [ ]:
features =data2['Comments'].tolist()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf = TfidfVectorizer(stop_words = 'english')

In [ ]:
tf_matrix = tf.fit_transform(features)

In [ ]:
tf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
similarity = cosine_similarity(tf_matrix)

In [ ]:
pd.DataFrame(similarity)

0         1         2         3         4         5         6     \
0     1.000000  0.041729  0.029688  0.000000  0.047728  0.011535  0.019475   
1     0.041729  1.000000  0.008025  0.113145  0.048878  0.007811  0.053314   
2     0.029688  0.008025  1.000000  0.000000  0.055422  0.026158  0.000000   
3     0.000000  0.113145  0.000000  1.000000  0.000000  0.000000  0.000000   
4     0.047728  0.048878  0.055422  0.000000  1.000000  0.008976  0.028657   
...        ...       ...       ...       ...       ...       ...       ...   
2442  0.000000  0.000000  0.000000  0.000000  0.000000  0.031029  0.000000   
2443  0.028744  0.007865  0.005622  0.000000  0.009039  0.028596  0.009238   
2444  0.031255  0.021163  0.006011  0.023798  0.009664  0.005850  0.057857   
2445  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2446  0.029508  0.039465  0.014428  0.000000  0.108134  0.000000  0.046190   

          7         8         9     ...      2437      2438      2439  \
0     0.043804  0.088598  0.000000  ...  0.055464  0.046579  0.010022   
1     0.011985  0.029856  0.000000  ...  0.000000  0.063869  0.006786   
2     0.008568  0.008480  0.012856  ...  0.035206  0.000000  0.024248   
3     0.084658  0.000000  0.000000  ...  0.046459  0.000000  0.000000   
4     0.013774  0.013633  0.020669  ...  0.000000  0.000000  0.038983   
...        ...       ...       ...  ...       ...       ...       ...   
2442  0.000000  0.000000  0.000000  ...  0.028030  0.044645  0.000000   
2443  0.020779  0.008311  0.000000  ...  0.000000  0.007305  0.036917   
2444  0.008977  0.060181  0.000000  ...  0.020175  0.012149  0.005083   
2445  0.000000  0.000000  0.038007  ...  0.029492  0.000000  0.000000   
2446  0.031613  0.000000  0.015802  ...  0.000000  0.006228  0.000000   

          2440      2441      2442      2443      2444      2445      2446  
0     0.000000  0.031248  0.000000  0.028744  0.031255  0.000000  0.029508  
1     0.000000  0.008550  0.000000  0.007865  0.021163  0.000000  0.039465  
2     0.021580  0.006112  0.000000  0.005622  0.006011  0.000000  0.014428  
3     0.000000  0.025897  0.000000  0.000000  0.023798  0.000000  0.000000  
4     0.028270  0.009826  0.000000  0.009039  0.009664  0.000000  0.108134  
...        ...       ...       ...       ...       ...       ...       ...  
2442  0.000000  0.053986  1.000000  0.031244  0.000000  0.000000  0.000000  
2443  0.000000  0.014823  0.031244  1.000000  0.005891  0.000000  0.006928  
2444  0.000000  0.016428  0.000000  0.005891  1.000000  0.000000  0.000000  
2445  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.019508  
2446  0.014693  0.062725  0.000000  0.006928  0.000000  0.019508  1.000000  

[2447 rows x 2447 columns]

In [ ]:
def rest_rec_sys(name,similarity=similarity):
  index = indices[name]
  similarity_score = list(enumerate(similarity[index]))
  similarity_score = sorted(similarity_score,key = lambda x:x[1],reverse = True)
  similarity_score = similarity_score[0:11]
  res_indices =[i[0] for i in similarity_score]
  res_rec = data1['Name'].iloc[res_indices]
  return res_rec

In [ ]:
rest_rec_sys('Maywood Pancake house')

2457                      Le Vallauris
259                        Bis on Main
1901               D'Carbon Restaurant
2023                       Nomad Pizza
2201        Tokyo Japanese Steak House
601                 Genesee Brew House
1550                    Fortune Buffet
2324                   Lapisara Eatery
1651                 Pho Saigon Garden
441              Tony P's House of Pie
962     Truluck's Seafood Steak & Crab
Name: Name, dtype: object